name: Tests
on: [push, pull_request]

jobs:
    test:
        name: PHP ${{ matrix.php }} (${{ matrix.dependency-version }})
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [ubuntu-latest, windows-latest, macos-latest]
                php: [8.0]
                dependency-version: [highest, lowest]
        steps:
            - uses: actions/checkout@v2

            - name: Configure PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php }}
                  extensions: mbstring
                  coverage: none

            - name: Install dependencies
              uses: ramsey/composer-install@v1
              with:
                dependency-versions: ${{ matrix.dependency-version }}
                composer-options: "--prefer-dist"

            - name: Execute tests
              run: vendor/bin/phpunit
